create table public.products (
  id bigint primary key generated by default as identity,
  name text not null,
  price numeric(10, 2) not null check (price >= 0),
  image text not null,
  category text not null
);

alter table public.products enable row level security;

create policy "Products are readable by everyone"
on public.products for select
using (true);

create table public.cart_items (
  id bigint primary key generated by default as identity,
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  quantity integer not null default 1 check (quantity between 1 and 10),
  unique (user_id, product_id)
);

alter table public.cart_items enable row level security;

create policy "Users can read their own cart"
on public.cart_items for select
using ((select auth.uid()) = user_id);

create policy "Users can add to their own cart"
on public.cart_items for insert
with check ((select auth.uid()) = user_id);

create policy "Users can update their own cart"
on public.cart_items for update
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Users can delete their own cart"
on public.cart_items for delete
using ((select auth.uid()) = user_id);

insert into public.products (id, name, price, image, category) values
  (1, 'Wireless Mouse', 799, '/images/products/mouse.jpg', 'Electronics'),
  (2, 'Coffee Mug', 249, '/images/products/mug.jpg', 'Home'),
  (3, 'Mechanical Keyboard', 2499, '/images/products/keyboard.jpg', 'Electronics'),
  (4, 'Desk Lamp', 1299, '/images/products/lamp.jpg', 'Home'),
  (5, 'Water Bottle', 599, '/images/products/bottle.jpg', 'Fitness'),
  (6, 'Notebook', 199, '/images/products/notebook.jpg', 'Stationery'),
  (7, 'Headphones', 1799, '/images/products/headphone.jpg', 'Electronics'),
  (8, 'Backpack', 1499, '/images/products/backpack.jpg', 'Accessories'),
  (9, 'Coffee Beans', 699, '/images/products/coffee-bean.jpg', 'Grocery'),
  (10, 'Phone Stand', 399, '/images/products/phone-stand.jpg', 'Accessories');

select setval(
  pg_get_serial_sequence('public.products', 'id'),
  coalesce((select max(id) from public.products), 1)
);
